<h1><?php echo $this->__('MasterPass') ?></h1>
<div class="box-account">
  <div class="box-head">
    <h2><?php echo $this->__('Connect with MasterPass') ?></h2>
  </div>
  <div class="securesubmit-connect-with-masterpass">
    <?php $longAccessToken = $this->getLongAccessToken(); ?>
    <?php if ($longAccessToken): ?>
      <form method="POST">
        <input type="hidden" name="forget_masterpass" value="true">
        <input type="submit" value="Disconnect">
      </form>
    <?php else: ?>
      <button type="button"
              class="button"
              onclick="jQuery(this).attr('disabled', 'disabled').val('Processing'); jQuery(this).parents('form').submit(); return false;"
              id="securesubmit-connect-with-masterpass">
        <img src="https://www.mastercard.com/mc_us/wallet/img/en/US/mp_connect_with_button_034px.png"
             alt="Connect with MasterPass" />
      </button>
    <?php endif; ?>
  </div>
</div>
