<ul class="form-list" id="payment_form_<?= $this->getMethodCode(); ?>" style="display:none;">
  <li>
    <?php echo Mage::helper('hps_securesubmit')->__('You will be redirected to the MasterPass site.'); ?>
  </li>
  <li>
    <?php $cards = $this->getCards(); ?>
    <?php if ($cards && !empty($cards)): ?>
      <input type="hidden" id="<?= $this->getMethodCode(); ?>_connected" value="true" />
      <h6>Credit Cards</h6>
      <?php foreach ($cards as $card): ?>
        <label>
          <input type="radio"
                 name="masterpass_card_id"
                 value="<?= $card->CardId; ?>"
                 <?php if ($card->SelectedAsDefault == 'true'): ?> checked="checked"<?php endif;?> />
          <?= $card->BrandName; ?>
          ending in <?= $card->LastFour; ?>
          expiring <?= $card->ExpiryMonth; ?>/<?= $card->ExpiryYear; ?>
          <?php if ($card->SelectedAsDefault == 'true'): ?>(default)<?php endif; ?>
        </label><br />
      <?php endforeach; ?>
    <?php endif; ?>
  </li>
</ul>
