<img src="<?php echo $this->escapeHtml($this->getMarkSrc())?>" alt="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('hps_securesubmit')->__('Acceptance Mark')) ?>" class="v-middle" />&nbsp;
<a href="<?php echo $this->getMarkHref()?>" onclick="javascript:window.open('<?php echo $this->getMarkHref()?>','masterpasslearnmore','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, ,left=0, top=0, width=624, height=350'); return false;">
    <?php echo Mage::helper('hps_securesubmit')->__('Learn more'); ?>
</a>
