<?php
    //GET SESSION DATA
    Mage::getSingleton('core/session', array('name'=>'frontend'));
    $session = Mage::getSingleton('customer/session');

    $_code=$this->getMethodCode();
    $_model = Mage::getModel('hps_securesubmit/payment');
    $public_key = $_model->getConfigData('publicapikey');
?>
<fieldset class="form-list">
<ul id="payment_form_<?php echo $_code ?>" style="display:none">  
    <li>  
        <div class="input-box">  
            <label for="<?php echo $_code ?>_cc_number"><?php echo $this->__('Credit Card Number') ?> <span class="required">*</span></label><br>  
            <input type="text" id="<?php echo $_code ?>_cc_number" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="">  
            <input type="hidden" id="<?php echo $_code ?>_token" name="payment[securesubmit_token]" value="">
        </div>  
    </li>  
    <li>  
        <div class="input-box">  
            <label for="<?php echo $_code ?>_expiration"><?php echo $this->__('Expiration Date') ?> <span class="required">*</span></label><br>  
            <div class="v-fix">  
            <select id="<?php echo $_code ?>_expiration" class="month required-entry validate-cc-exp">  
            <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>  
            <?php foreach ($this->getCcMonths() as $k=>$v): ?>  
                <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>  
            <?php endforeach ?>  
            </select>  
            </div>  
            <div class="v-fix">  
            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>  
            <select id="<?php echo $_code ?>_expiration_yr" class="year required-entry">  
            <?php foreach ($this->getCcYears() as $k=>$v): ?>  
                <option value="<?php echo $k?$k:'' ?>" <?php if($k==$_ccExpYear):?> selected="selected"<?php endif ?>><?php echo $v ?></option>  
            <?php endforeach ?>  
            </select>  
            </div>  
        </div>  
    </li>  
    <li>  
        <div class="input-box">  
            <label for="<?php echo $_code ?>_cc_cid"><?php echo $this->__('Card Verification Number') ?> <span class="required">*</span></label><br>  
            <div class="v-fix"><input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="cvv required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" value=""></div>  

            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>  
        </div>  
    </li>
    <li>
        <div class="input-box" id="cc_save_future">
            <div class="v-fix">
                <input type="checkbox" id="<?php echo $_code ?>_cc_save_future" name="payment[cc_save_future]" value="Y" />
            </div>
            <label for="<?php echo $_code ?>_cc_save_future">&nbsp;<?php echo $this->__('Save this card for future use') ?></label>
        </div>
    </li>
</ul>
</fieldset>

<script type="text/javascript">
//<![CDATA[

function hideStoreCard(){
    guest = document.getElementById('login:guest').checked;
    if(guest){
        document.getElementById("cc_save_future").style.display = 'none';
    }
}

window.onload = hideStoreCard();

function secureResponseHandler(response) {
    if (response.message) {
        alert(response.message);
        checkout.setLoadWaiting(false);
    } else {
        $('<?php echo $_code ?>_token').value = response.token_value;

        if(document.getElementById('<?php echo $_code ?>_cc_save_future').checked){
            saveToken(response);
        }

        var request = new Ajax.Request(
             payment.saveUrl,
             {
                 method:'post',
                 onComplete: payment.onComplete,
                 onSuccess: payment.onSave,
                 onFailure: checkout.ajaxFailure.bind(checkout),
                 parameters: Form.serialize(payment.form)
             }
         );
    }
}

Object.extend(Payment.prototype, {
    save: function() {
        if (this.currentMethod == "hps_securesubmit") {
            if (checkout.loadWaiting!=false)
                return;
            var validator = new Validation(this.form);
            if (this.validate() && validator.validate()) {
                checkout.setLoadWaiting('payment');

                hps.tokenize({
                    data: {
                        public_key: '<?php echo $public_key ?>',
                        number: document.getElementById('<?php echo $_code ?>_cc_number').value,
                        cvc: document.getElementById('<?php echo $_code ?>_cc_cid').value,
                        exp_month: document.getElementById('<?php echo $_code ?>_expiration').value,
                        exp_year: document.getElementById('<?php echo $_code ?>_expiration_yr').value
                    },
                    success: function(response) {
                        secureResponseHandler(response);
                    },
                    error: function(response) {
                        secureResponseHandler(response);
                    }
                });
            }
        } else {
            if (checkout.loadWaiting != false)
                return;
            var validator = new Validation(this.form);
            if (this.validate() && validator.validate()) {
                checkout.setLoadWaiting('payment');
                var request = new Ajax.Request(
                    this.saveUrl,
                    {
                        method:'post',
                        onComplete: this.onComplete,
                        onSuccess: this.onSave,
                        onFailure: checkout.ajaxFailure.bind(checkout),
                        parameters: Form.serialize(this.form)
                    }
                );
            }
        }
    }
});

function saveToken(tokenData){
    var baseUrl = "<?php echo Mage::getUrl('');?>";
    var url = baseUrl + "securesubmit/saveToken/saveToken";
    var token = tokenData.token_value;
    var customer_id = <?php echo $session->getCustomer()->getId(); ?>;
    var last_four = tokenData.card.number;
    var month_selector = document.getElementById('<?php echo $_code ?>_expiration');
    var exp_month = month_selector.options[month_selector.selectedIndex].text.substr(0,2);
    var exp_year = document.getElementById('<?php echo $_code ?>_expiration_yr').value;
    var card_type = "";

    var card_types = {Amex: /^3[47][0-9]{13}$/,
                MasterCard: /^5[1-5][0-9]{14}$/,
                Visa: /^4[0-9]{12}(?:[0-9]{3})?$/,
                DinersClub: /^3(?:0[0-5]|[68][0-9])[0-9]{11}$/,
                EnRoute: /^(2014|2149)/,
                Discover: /^6(?:011|5[0-9]{2})[0-9]{12}$/,
                Jcb: /^(?:2131|1800|35\d{3})\d{11}$/};

    if(document.getElementById('<?php echo $_code ?>_cc_number') != null){
        card = document.getElementById('<?php echo $_code ?>_cc_number').value;
        for(key in card_types){
            if(card.match(card_types[key]) != null){
                card_type = key;
            }
        }
    }

    new Ajax.Request(url, {
        method: "post",
        parameters: {customer_id: customer_id,
                    token: token,
                    card_last_four:last_four.substr(-4),
                    card_exp_month:exp_month,
                    card_exp_year:exp_year,
                    card_type: card_type},
        onFailure: function(response){
            var json = JSON.parse(response.responseText);
            console.log(json.error.message);
            HPS.error(json.error.message);
        }
    });
}
//]]>
</script>
