<?php /** @var $this Hps_Securesubmit_Block_Adminhtml_Form */
$_code = $this->getMethodCode();
$customerStoredCards = $this->getCustomerStoredCards();
$useStoredCard = !! $this->getInfoData('securesubmit_use_stored_card');
$public_key = Mage::getModel('hps_securesubmit/payment')->getConfigData('publicapikey');
$customerId = Mage::getSingleton('adminhtml/session_quote')->getCustomerId();
$customerStoredCards = Mage::helper('hps_securesubmit')->getStoredCards( $customerId );
$allow_card_saving = Mage::getModel('hps_securesubmit/payment')->getConfigData('allow_card_saving');
?>

<input id="<?php echo $_code ?>_payment_method" type="hidden" name="payment[method]" value="<?php echo $_code ?>" />
<ul id="payment_form_<?php echo $_code ?>" class="form-list" style="display:none;">
    <?php if($allow_card_saving && count($customerStoredCards)): ?>
        <li>
            <label for="<?php echo $_code ?>_stored_card_checkbox"><?php echo $this->__('Use a stored card') ?></label>
            <div class="input-box">
                <input type="checkbox" id="<?php echo $_code ?>_stored_card_checkbox" name="payment[securesubmit_use_stored_card]" <?php if ($useStoredCard) : ?> checked="checked" <?php endif ?> value="1" />
            </div>
        </li>
        <li id="<?php echo $_code ?>_stored_cards" style="display: none">
            <label for="<?php echo $_code ?>_stored_card_select"><?php echo $this->__('Stored Card') ?></label>
            <div class="input-box">
                <select id="<?php echo $_code ?>_stored_card_select"  autocomplete="off">
                    <?php foreach ($customerStoredCards as $key => $card): ?>
                        <option value="<?php echo $card->getId() ?>"><?php echo $card->getCcType().' ************'.$card->getCcLast4().' ('.$card->getCcExpMonth().'/'.$card->getCcExpYear().')' ?></option>
                    <?php endforeach ?>
                </select>
            </div>
        </li>
    <?php endif ?>
    <li class="stored_cards_selected">
        <label for="<?php echo $_code ?>_cc_type" ><?php echo Mage::helper('payment')->__('Credit Card Type') ?><span class="required">*</span></label>
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName) : ?>
                    <option value="<?php echo $_typeCode ?>"<?php if($_typeCode == $_ccType) : ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <li class="stored_cards_selected">
        <label for="<?php echo $_code ?>_cc_number"><?php echo Mage::helper('payment')->__('Credit Card Number') ?><span class="required">*</span></label>
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" data-encrypted-name="payment[cc_number]"  title="<?php echo Mage::helper('payment')->__('Credit Card Number') ?>"  class="input-text validate-cc-number validate-cc-type" value=""/>
            <input type="hidden" id="<?php echo $_code ?>_token" name="payment[securesubmit_token]" value="">
            <input type="hidden" id="<?php echo $_code ?>_cc_last_four" name="payment[cc_last_four]" value="">
        </div>
    </li>
    <li class="stored_cards_selected">
        <div class="input-box">
            <label for="<?php echo $_code ?>_expiration"><?php echo Mage::helper('payment')->__('Expiration Date') ?> <span class="required">*</span></label><br/>
            <select id="<?php echo $_code ?>_expiration" style="width:140px;" name="payment[cc_exp_month]" class="validate-cc-exp required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k ?>" <?php if($k==$_ccExpMonth): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
            <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
            <select id="<?php echo $_code ?>_expiration_yr" style="width:103px;" name="payment[cc_exp_year]" class="required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k ? $k : '' ?>" <?php if($k==$_ccExpYear): ?>selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
            </select>
        </div>
    </li>
    <?php if($this->hasVerification()): ?>
        <li class="stored_cards_selected">
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_cid"><?php echo Mage::helper('payment')->__('Card Verification Number') ?> <span class="required">*</span></label><br/>
                <input type="text" title="<?php echo Mage::helper('payment')->__('Card Verification Number') ?>" class="required-entry input-text validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" style="width:3em;" value=""/>
            </div>
        </li>
    <?php endif; ?>

    <?php if ($allow_card_saving && $public_key): ?>
        <li class="stored_cards_selected">
            <label for="<?php echo $_code ?>_cc_save_future"><?php echo $this->__('Save this card for future use?') ?></label>
            <div class="input-box">
                <input type="checkbox" id="<?php echo $_code ?>_cc_save_future" name="payment[cc_save_future]" value="Y" autocomplete="off" />
                <input type="hidden" id="<?php echo $_code ?>_customer_id" name="payment[customer_id]" value="<?php echo $customerId; ?>" />
            </div>
        </li>
    <?php endif ?>
</ul>
<script type="text/javascript">
//<![CDATA[

<?php if($allow_card_saving && count($customerStoredCards)): ?>
$('<?php echo $_code ?>_stored_card_checkbox').observe('click',function() {
    $$('.stored_cards_selected').invoke('toggle');
    $('<?php echo $_code ?>_stored_cards').toggle();
    $('<?php echo $_code ?>_cc_number').toggleClassName('validate-cc-number');
});
<?php endif ?>

order.secureSubmitPublicKey = '<?php echo $public_key ?>';
order.secureSubmitGetTokenDataUrl = '<?php echo Mage::getUrl('securesubmit/storedcard/getTokenData', array('_secure' => TRUE)) ?>';

<?php if (count($customerStoredCards)) : ?>
    var customerStoredCards = <?php echo json_encode($this->getJsConfig()) ?>;
    $('<?php echo $_code ?>_stored_card_checkbox').observe('click',function() {
        toggleStoredCards();
    });
    function toggleStoredCards() {
        // Toggle between the saved credit cards and a new card form
        $$('.stored_cards_selected').invoke('toggle');
        $('<?php echo $_code ?>_stored_cards').toggle();
        $('<?php echo $_code ?>_cc_type').toggleClassName('validate-cc-type-select').toggleClassName('required-entry');
        $('<?php echo $_code ?>_cc_number').toggleClassName('validate-cc-number');
        $('<?php echo $_code ?>_cc_cid').toggleClassName('validate-cc-cvn').toggleClassName('required-entry');
        $('<?php echo $_code ?>_use_credit_card').value = $('<?php echo $_code ?>_stored_card_checkbox').checked ? '0' : '1';

        // Set credit card information
        var creditCardId = $('<?php echo $_code ?>_stored_card_select').value;
        if (customerStoredCards[creditCardId]) {
            var creditCardData = customerStoredCards[creditCardId];
            $('<?php echo $_code ?>_expiration').value = parseInt(creditCardData.cc_exp_month);
            $('<?php echo $_code ?>_expiration_yr').value = creditCardData.cc_exp_year;
            $('<?php echo $_code ?>_token').value = creditCardData.token_value;
            $('<?php echo $_code ?>_cc_last_four').value = creditCardData.cc_last_four;
        }
    }
    <?php if ($useStoredCard) : ?>
        toggleStoredCards();
    <?php endif ?>
<?php endif ?>
//]]>
</script>
