<?php /** @var $this Hps_Securesubmit_Block_Adminhtml_Transaction */ ?>
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-products"><?php echo $this->getHeaderText() ?></h3></td>
        </tr>
    </table>
</div>
<?php echo $this->getStoreSwitcherHtml() ?>
<?php if ( ! $this->isSingleStoreMode()) : ?>
    <?php echo $this->getChildHtml('store_switcher') ?>
<?php endif;?>
<div>
    <?php echo $this->getGridHtml() ?>
</div>
